services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: minha_aplicacao
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "src/main.py"]

volumes:
  pgdata:
